import type { Metadata } from "next";
import { ApolloWrapper } from "@/components/ApolloWrapper";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <body
            suppressHydrationWarning
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <ApolloWrapper>
                <Toaster
                    position="top-right" // Posição
                    toastOptions={{
                        duration: 4000, // 4 segundos
                        style: {
                            background: '#333',
                            color: '#fff',
                        },
                    }}
                />
                {children}
            </ApolloWrapper>
        </body>
    );
}